CREATE TABLE PERSON (
   ID             BIGINT        NOT NULL PRIMARY KEY,
   FIRST_NAME     VARCHAR (30)  NOT NULL,
   LAST_NAME      VARCHAR (30)  NOT NULL
);

INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Forrest', 'Gump');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Jeffrey', 'Lebowski');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'John', 'Connor');
